// packages/website-2/src/components/solid/markdown/MarkdownGuideNav.tsx
import {Progress} from "@kobalte/core/progress";
import type { Component } from "solid-js";

import MarkdownGuideNavButton from "@/components/solid/markdown/MarkdownGuidedNavButton.tsx";

interface MarkdownGuideNavProps {
  backHref?: string;
  backText?: string;
  forwardHref?: string;
  forwardText?: string;
  stepNumber: number;
  totalSteps: number;
  progressLabel?: string;
}

const MarkdownGuideNav: Component<MarkdownGuideNavProps> = (props) => {
  return (

    <Progress
      minValue={1}
      maxValue={props.totalSteps}
      value={props.stepNumber}
      getValueLabel={({ value, max }) => `Step ${value} of ${max}`}
      class="flex w-full flex-col gap-4 py-4"
    >
      <div class="flex items-end justify-between gap-4">
        <MarkdownGuideNavButton
          href={props.backHref}
          text={props.backText || "Back"}
          icon={"left"}
        />
        <div class="flex justify-center gap-4">
        <Progress.Label class="text-display-xs font-semibold">
          {props.progressLabel || "Guide Progress"}
        </Progress.Label>
        <Progress.ValueLabel />
        </div>
        <MarkdownGuideNavButton
          href={props.forwardHref}
          text={props.forwardText || "Next"}
          icon={"right"}
        />
      </div>

      <Progress.Track
        class="bg-tertiary dark:bg-secondary h-2 rounded"
      >
        <Progress.Fill
          class="bg-accent h-full w-[var(--kb-progress-fill-width)]"
        />
      </Progress.Track>
    </Progress>
  )
};

export default MarkdownGuideNav;

// packages/website-2/react/markdown/MarkdownGuideNav.tsx
import { faArrowLeft, faArrowRight } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { memo } from "react";
import { Button } from "@/components/react/ui/Button.tsx";
import { Progress } from "@/components/react/ui/progress";

function MarkdownGuideNavButton(props: {
  href: string | undefined;
  tooltip: string;
  text: string;
  icon: "left" | "right";
}) {
  const { href, tooltip, text, icon } = props;

  if (href === undefined) {
    return <div className="w-36" />;
  }

  return (
    <Button asChild variant={`primary`}>
      <a href={href} className={`flex items-center gap-x-xs `}>
        {icon === "right" ? null : (
          <FontAwesomeIcon icon={faArrowLeft} size="lg" />
        )}
        {text}
        {icon === "left" ? null : (
          <FontAwesomeIcon icon={faArrowRight} size="lg" />
        )}
      </a>
    </Button>
  );
}

interface MarkdownGuideNavProps {
  backHref?: string | undefined;
  backText?: string | undefined;
  backTooltip?: string | undefined;
  forwardHref?: string | undefined;
  forwardText?: string | undefined;
  forwardTooltip?: string | undefined;
  stepNumber?: number | undefined;
  totalSteps?: number | undefined;
  progressLabel?: string | undefined;
}

export default memo(function MarkdownGuideNav(props: MarkdownGuideNavProps) {
  const {
    backHref,
    backText = "Previous",
    backTooltip = "Previous page",
    forwardHref,
    forwardText = "Next",
    forwardTooltip = "Next page",
    stepNumber,
    totalSteps = 10,
    progressLabel,
  } = props;

  return (
    <div className="w-full flex flex-col gap-2 py-4 not-prose">
      <div className=" flex justify-between items-end">
        <MarkdownGuideNavButton
          href={backHref}
          text={backText}
          tooltip={backTooltip}
          icon={"left"}
        />
        {stepNumber === undefined ? (
          <div />
        ) : (
          <div className="justify-center gap-3 hidden lg:flex">
            <div className="font-bold">{progressLabel}</div>
            <div>
              {" "}
              Step {stepNumber} /{totalSteps}
            </div>
          </div>
        )}
        <MarkdownGuideNavButton
          href={forwardHref}
          text={forwardText}
          tooltip={forwardTooltip}
          icon={"right"}
        />
      </div>
      {stepNumber === undefined ? (
        <div />
      ) : (
        <div className="flex flex-col gap-3">
          <Progress
            color="primary"
            value={Math.round((stepNumber / totalSteps) * 100)}
          />
          <div className="justify-center gap-3 flex lg:hidden text-base">
            <div className="font-bold">{progressLabel}</div>
            <div>
              {" "}
              Step {stepNumber} /{totalSteps}
            </div>
          </div>
        </div>
      )}
    </div>
  );
});
